declare module 'react-native' { declare module.exports: any; }
declare module 'react-navigation' { declare module.exports: any; }
declare module 'react-redux' { declare module.exports: any; }
declare module 'redux-persist-transform-immutable' { declare module.exports: any; }
declare module 'react-navigation-redux-helpers' { declare module.exports: any; }
declare module 'immutable' { declare module.exports: any; }
declare module 'redux' { declare module.exports: any; }
declare module 'redux-logger' { declare module.exports: any; }
declare module 'redux-persist' { declare module.exports: any; }
declare module 'redux-persist/es/integration/react' { declare module.exports: any; }
declare module 'redux-thunk' { declare module.exports: any; }
declare module 'remote-redux-devtools' { declare module.exports: any; }
declare module './utils/automergeLevel2-immutable' { declare module.exports: any; }
declare module 'react-native-console-time-polyfill' { declare module.exports: any; }
declare module 'react-devtools' { declare module.exports: any; }
declare module 'core-js' { declare module.exports: any; }
