# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativePlatform' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativePlatform
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore', '5.1.0'

  target 'ReactNativePlatformTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativePlatform-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativePlatform-tvOS

  target 'ReactNativePlatform-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
